### ISSUE TITLE
segfault on master and latest stable when mirroring Packagist

### ISSUE THREAD

**Issue by fabpot** [rande/pkgmirror#24]
Here is the run:

```
pkgmirror/build/darwin-amd64-pkgmirror run -file pkgmirror.toml
Configure app
Start app lifecycle
INFO[0000] Init                                          code=packagist handler=composer server=https://packagist.org
Start HTTP Server (bind: :8765)
INFO[0000] Starting Composer Service                     code=packagist handler=composer server=https://packagist.org
INFO[0000] Starting a new sync...                        code=packagist handler=composer server=https://packagist.org
INFO[0000] Start the SSE Broker
INFO[0000] Starting SyncPackages                         action=SyncPackages code=packagist handler=composer server=https://packagist.org
INFO[0000] Loading packages.json                         action=SyncPackages code=packagist handler=composer server=https://packagist.org
INFO[0001] Loading provider information                  action=SyncPackages code=packagist handler=composer hash=664617ca8865fd21d411eb1559a93d5c4609a2203da3630d9953b219e8384f33 provider=p/provider-2015$%hash%.json server=https://packagist.org
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d0a29]

goroutine 19 [running]:
panic(0x4617e0, 0xc4200120f0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/rande/pkgmirror/vendor/github.com/boltdb/bolt.(*DB).beginTx(0x0, 0xffffffffffffffff, 0xc420049960, 0x12ac5)
	rande/pkgmirror/vendor/github.com/boltdb/bolt/db.go:470 +0x29
github.com/rande/pkgmirror/vendor/github.com/boltdb/bolt.(*DB).Begin(0x0, 0xc42030a700, 0xc4208d3280, 0xc420049988, 0xe9eb)
	rande/pkgmirror/vendor/github.com/boltdb/bolt/db.go:463 +0x6e
github.com/rande/pkgmirror/vendor/github.com/boltdb/bolt.(*DB).View(0x0, 0xc420049d08, 0x0, 0x0)
	rande/pkgmirror/vendor/github.com/boltdb/bolt/db.go:610 +0x46
github.com/rande/pkgmirror/mirror/composer.(*ComposerService).SyncPackages(0xc4201a3470, 0xc42020df80, 0x1)
	rande/pkgmirror/mirror/composer/composer.go:226 +0x1083
github.com/rande/pkgmirror/mirror/composer.(*ComposerService).Serve.func1()
	rande/pkgmirror/mirror/composer/composer.go:77 +0xcd
created by github.com/rande/pkgmirror/mirror/composer.(*ComposerService).Serve
	rande/pkgmirror/mirror/composer/composer.go:85 +0x15a
```

```toml
DataDir = "/Users/fabien/packagist-miror/data"
CacheDir = "/Users/fabien/packagist-miror/cache"
PublicServer = "http://127.0.0.1"
InternalServer = ":8765"

[Composer]
    [Composer.packagist]
    Server = "https://packagist.org"
    Enabled = true
    Icon = "https://getcomposer.org/img/logo-composer-transparent.png"
```

**Comment by rande** [comment]
Can you try to run those commands?

```
mkdir /Users/fabien/packagist-miror/data
mkdir /Users/fabien/packagist-miror/cache
```

I will rebuild a new version with more checks ;)

**Comment by fabpot** [comment]
I created the directory before running the command, so the problem is elsewhere. I've just double-checked, and I do have these directories (empty).

**Comment by rande** [comment]
related PR: https://github.com/rande/pkgmirror/pull/26

**Comment by fabpot** [comment]
Looks like it does not segfault anymore, thanks!
